### PR TITLE
Paginate assignment  mentor

### PR DESCRIPTION
**Pull request by chikamichi**

### CODE REVIEW

**Comment by chikamichi** [comment]
So, you'll want to use https://github.com/UJKhokhar/bloccit/pull/6/commits to review the new commits I pushed that we reviewed together (if you want).

**Comment by UJKhokhar** [comment]
Wouldn't let me merge through github button because of conflicts so did it manually.

**Comment by chikamichi** [comment]
Excellent. When the time is right (when starting the projects), I'll show you another way to manage topic branches that makes it less frequent to have conflicts like this. Good job!

**Comment by UJKhokhar** [comment]
Sounds good. Thanks :D

**Pull request merged**
