### PR TITLE
Several improvements to the authorization management

### PR DESCRIPTION
**Pull request by chikamichi**
This portion of the schema was added when you worked on the Ad assignment a few checkpoints back. It's useless on the master branch, though.

This is an example of a pull-request. I forked your repository (ie. created a copy on my own GitHub account), did some changes, commited, and now I ask whether this could be merged back into your "upstream" version (the main version, that is!).

### CODE REVIEW

**Comment by chikamichi** [comment]
I made several improvements to the authorization management. It's not expected that you merge this pull request into your codebase, but we could review this together as a way to discuss about Pundit, Rails and Ruby in general. And git. :sunglasses:

**Comment by chikamichi** [comment]
And git. :sunglasses:

**Comment by chikamichi** [comment]
It's up to you whether you want to merge this PR into your code. It won't conflict with the next checkpoints, but if you don't feel comfortable with it, you can close it :)

**Comment by chikamichi** [comment]
If yo chose to merge, don't forget you would have to implement the edge-case of the `nil` role inside `user_is?`.

**Comment by chikamichi** [comment]
:fireworks:  Your first pull-request, I guess, isn't it?

**Comment by UJKhokhar** [comment]
Yup, was there a step I missed?

**Comment by chikamichi** [comment]
You merged successfully, so everything's fine. I guess you used the green merge button on GitHub, right? It means that a couple of commits were added to the project's history here on GitHub, and you don't have those commits in your local repository yet. In order to sync with GitHub, you must pull in the changes: `git pull` (short for `git pull origin maser`), while on the `master` branch.

**Comment by UJKhokhar** [comment]
Hmm I actually used command line instructions that were provided here. 
```
git checkout -b chikamichi-master master
git pull https://github.com/chikamichi/bloccit.git master
git checkout master
git merge --no-ff chikamichi-master
git push origin master
```

**Comment by chikamichi** [comment]
Also, don't forget to fix the `nil` edge-case, as referenced above. Reminder: we want to be able to call `user_is?` with the `nil` role, which is the "default role" (regular user):

``` ruby
user_is?(nil, 'moderator') # checks whether the user is a regular user or a moderator
```

We can't just do `user.send("nil?")`, because this is not a role check: it returns whether `user` is `nil`! So we would need to add some kind of `regular_user?` method to the `User` model, and use that within `user_is?`.

**Comment by chikamichi** [comment]
Oh, perfect! You merged the pull-request from your local environment. Nice. Do all the git commands make sense to you?

**Comment by chikamichi** [comment]
By the way, if you don't like `user_is?(nil)` because it's not really meaningful, you might want to use a different value than `nil`, like `regular`. But this is brittle code, because you might one day add a role named `regular` that's different from the default `nil` role. Very unlikely, but… Maybe a better way to handle roles would have been to provide a default, meaningful value (not that weird `nil`). It's never too late though, it's your application!

**Comment by UJKhokhar** [comment]
Okay, got it. I'm working on the edge case right now. 

I wasn't sure what ```git merge --no-ff``` was at first but I read about it [here.] (http://stackoverflow.com/questions/9069061/what-is-the-difference-between-git-merge-and-git-merge-no-ff) It seems to make sure that commits are available locally as well.

**Comment by chikamichi** [comment]
Not exactly, but it's not very important right now, so we'll get back to this `--no-ff` option later during a meeting (*adding that to the TOREVIEW list*)

**Comment by chikamichi** [comment]
Quick note: when doing the Topics & Posts checkpoint (which you already started IIRC), be sure to use `ApplicationPolicy`'s API (that is, `user_exists'`, `user_is?`, `record_exists?`, `record_owned_by_user?`) so that everything is consistent :)

**Pull request merged**
